version: 1.0
provider:
  name: openfaas
  gateway: http://192.168.122.138:31112
functions:
  product-purchase-goapi:
    lang: golang-kaiyu-http-tls
    handler: ./product-purchase-goapi
    image: posoo/product-purchase-goapi:tls2
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    environment:
      URL_PRODUCT_PURCHASE_GET_PRICE: 'https://192.168.122.138:31122/function/product-purchase-get-price'
      URL_PRODUCT_PURCHASE_AUTHORIZE_CC: 'https://192.168.122.138:31122/function/product-purchase-authorize-cc'
      URL_PRODUCT_PURCHASE_PUBLISH: 'https://192.168.122.138:31122/function/product-purchase-publish'
    secrets:
      - dockerhub