version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  product-catalog-api:
    lang: node10-express
    handler: ./product-catalog-api
    image: posoo/product-catalog-api:tcp3
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PRODUCT_CATEGORY_NAME: 'productCategory'
      TABLE_PRODUCT_CATALOG_NAME: 'productCatalog'
      HOST: 'mysql.openfaas-fn.svc.cluster.local'
      USER: 'abc'
      PASS: 'xyz'
    secrets:
      - dockerhub
