version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  product-purchase-get-price:
    lang: node10-express
    handler: ./product-purchase-get-price
    image: posoo/product-purchase-get-price:quic3
    read_timeout: 500 # seconds
    write_timeout: 500 # seconds
    exec_timeout: 0s # disable
    write_debug: true
    environment:
      DBNAME: 'helloRetail'
      TABLE_PRODUCT_PRICE_NAME: 'productPrice'
      HOST: 'mysql.openfaas-fn.svc.cluster.local'
      USER: 'abc'
      PASS: 'xyz'
    secrets:
      - dockerhub